### ISSUE TITLE
Typescript version of the template

### ISSUE THREAD

**Issue by dephiros** [Elderjs/template#10]
I am trying out elder js and see mentions of typescript in the doc. Is there a version of the template that supports Typescript out of the box?

Thank you for an awesome project

**Comment by nickreese** [comment]
@dephiros There isn't a ts template. I tried building one the day after typescript for svelte was released and kept hitting issues that were preventing me from shipping... mainly because I was unfamiliar with TS. 

That said, we do look for a tsconfig and will pick up the build folder if it exists. The entire template was in TS before I hit the snags trying to get TS to work in Svelte.

**Comment by dephiros** [comment]
Thank you @nickreese. As svelte is adopting TS more, maybe we can get some help to get the TS version working

**Comment by akvadrako** [comment]
There are still some mentions of Typescript, like to *hooks.ts* in *getting-started.md*. Maybe it would be nice to mention in the README what the plan is with Typescript - is it moving in that direction or away from it?

**Comment by nickreese** [comment]
@akvadrako I’d love to support TS long term. That said, I’m a novice compared to how comfortable I am in pure js and would prefer a real TS enthusiast help show me what a good TS template would look like.

**Comment by nickreese** [comment]
As an update to this. For v1+ of Elder.js you just need to set your ts build folder as your `srcDir` in your `elder.config.js` and follow the standard Svelte Typescript setup/preprocessor. Things should work out of the box from there.
